WIDTH, HEIGHT = 1500, 750
LOWER_MARGIN, SIDE_MARGIN = 90, 150

FPS = 60

# Tiles Constants
TILE_HEIGHT = 30
TILE_WIDTH = 30
ROWS = HEIGHT // TILE_HEIGHT
COLS = WIDTH // TILE_WIDTH
PIXEL_CORRECTION = 0.05

# Levels path
LEVELS_PATH: str = "levels/"
N_LEVELS = 1
